---
title: "Methods & Results Section"
output: html_notebook
bibliography: ["../packages_bibliography.bib"]
---

```{r, cache=TRUE, echo=FALSE}
suppressPackageStartupMessages(
  {
    library(tidyverse, quietly = TRUE)
    library(purrr, quietly = TRUE)
    library(stringr, quietly = TRUE)
    library(furrr, quietly = TRUE)
    library(lubridate, quietly = TRUE)
    library(broom, quietly = TRUE)
    library(knitr, quietly = TRUE)
    library(DAAG, quietly = TRUE)
    library(ROSE, quietly = TRUE)
    library(caret, quietly = TRUE)
    library(e1071, quietly = TRUE)
    library(readxl, quietly = TRUE)
    library(here, quietly = TRUE)
  }
)

all_surveys <- read_csv(here('DataOutputs','UpdatedSurveys_180713.csv')) %>%
  filter(complete.cases(.)) %>%
  mutate(Y = ifelse(EmotionalEatingEpisodes == 2, 'Control', 'Episode'))
df1 <- read_csv(here('DataOutputs','data_out_20181113 copy.csv'))
```

  Data analyses were carried out in `r R.version$version.string` and Python 2.7. In accordance with previous studies examining the relation between HRV and discrete eating episodes (Friesen et al., 2007; Harthoorn et al., 2008; Ranzenhofer et al., 2016), physiological data collected in the 30-minute period preceding the eating episode were examined. For each participant, the inter-beat interval (IBI) for each self-reported survey was selected, where surveys were either self-reported at the time of an eating episode, or pseudo-randomly triggered in the app. This resulted in an initial total of $n =$`r all_surveys %>% filter(Y == "Episode") %>% nrow()` emotional eating episodes and $n=$`r all_surveys %>% filter(Y == "Control") %>% nrow()` control episodes before cleaning.
Using the RHRV package [3], IBI data streams were filtered, interpolated, and artifacts were removed, using thresholds and parameters that complied with normative reported values for heart rate variability features [4]. Observations that did not meet normative criteria were removed. Features for analysis were extracted from both the time and frequency domain, which resulted in a total of n=19 emotional eating episodes and n=107 control episodes in the time domain, and n=15 emotional eating episodes and n=80 control episodes in the time domain.
The following heart rate variability features were extracted from the IBI streams for each observation in the time domain: SDNN (Standard Deviation of all filtered inter-beat intervals); SDANN (Standard Deviation of inter-beat intervals between all successive heartbeats); SDNNIX (Mean of the standard deviations of all the filtered inter-beat intervals for each 5 min segment of the IBI stream); pNN50 (Percentage of successive inter-beat intervals that differ by more than 50 ms); SDSD (Standard Deviation of Successive Differences of inter-beat intervals); rMSSD (Root Mean Square of Successive Differences); IRRR (length of the interval determined by the first and the third quantile of the inter-beat interval); MADRR (Median of the Absolute values of the successive Differences between the inter-beat intervals); TINN (Triangular Interpolation of inter-beat interval histogram); and HRVi (Heart Rate Variability index) [3]. 
	SDNN reflects the power of the components responsible for variability in heart rhythm, while SDANN, SDNNIX, pNN50, SDS, rMSSD, IRRR, and MADRR reflect different statistical aspects of the high frequency variation in heart rhythm. Finally, TINN and HRVi represent geometric measures calculated from the density distribution of inter-beat intervals.
	In the frequency domain, features extracted included the mean non-interpolated heart rate (mean niHR, the mean interpolated Heart Rate (mean HR), and the Heart Rates at the start and finish of the 30 minute window (Start HR, End HR). Additional frequency domain features were extracted from the 30 minute streams by applying a Fourier transform to the heart rate signal, resulting in a spectrogram of the heart rate in the low and high frequency ranges. To extract a sufficient amount of information from these spectograms and increase the variance of our data, the spectrogram was split into 5 minute windows, and features were extracted from each of these windows: the mean Low Frequency signal (LF1, LF2,… LF6); the mean High Frequency signal (HF1, HF2,… HF6); and the mean Low Frequency-High Frequency Ratio (LFHF1, LFHF2,… LFHF6).
	In order to examine any differences between means of the features, and address the issue of group imbalance affecting statistical power, we conducted between-groups permutation T-tests with each variable in the time and frequency domain[5]. Then, using the CARET package [6], a Support Vector Machine with a polynomial kernel was implemented to predict episodes from controls. In order to address the group imbalance in this stage, all features were standardized, while controls were randomly downsampled and episodes were randomly upsampled using the ROSE package [7]. To evaluate model performance, models were tested using 4-fold cross validation, training models on 3/4 of the data and using the remaining data evaluate the model accuracy, specificity, and sensitivity.