---
title: "Poster Plots"
output: html_notebook
---

Poster plots for October Conference

```{r}
#set the frequency features plot
gg_frequency = features_output%>%
  filter(!(Stress > 4 & Y == "Control"))%>% #filter high stress
  filter(ID %in% pp)%>%
  select(ID, Y, Avg_niHR:LFHF_6)%>%
  filter(complete.cases(.))%>%
  group_by(ID)%>%
  mutate_at(.vars = vars(Avg_niHR:LFHF_6), funs(scale))%>% #z score transform
  ungroup()%>%
  select(-ID)%>%
  gather("Feature", "Z_Score", 2:23)%>%
  mutate(Type = ifelse(str_detect(.$Feature, "HR"),
                       "Heart_Rate", ifelse(str_detect(.$Feature, "^HF"),
                                    "High_Frequency", ifelse(str_detect(.$Feature, "^LF_"), "Low_Frequency", "LF/HF_Ratio"))))

#set the time features plot
gg_time = features_output%>%
  filter(!(Stress > 4 & Y == "Control"))%>% #filter high stress
  filter(ID %in% pp)%>%
  select(ID, Y, SDNN:HRVi)%>%
  filter(complete.cases(.))%>%
  group_by(ID)%>%
  mutate_at(.vars = vars(SDNN:HRVi), funs(scale))%>% #z score transform
  ungroup()%>%
  select(-ID)%>%
  gather("Feature", "Z_Score", 2:11)


```

```{r}
gg_frequency%>%
  filter(Type != "High_Frequency" & Type != "Low_Frequency" & Type != "Heart_Rate")%>%
  ggplot(aes(x=Feature, y=Z_Score, fill = Y))+
  stat_summary(geom = "bar", fun.y = mean, position = "dodge")+
  stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge")+
  labs(title = "LF/HF Ratio Features By Condition",
       fill = "Condition")+
  theme_minimal()+
  scale_fill_viridis_d(alpha = 0.7)
```

```{r}
gg_frequency%>%
  filter(Type == "High_Frequency")%>%
  ggplot(aes(x=Feature, y=Z_Score, fill = Y))+
  stat_summary(geom = "bar", fun.y = mean, position = "dodge")+
  stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge")+
  labs(title = "High Frequency Domain Features By Condition",
       fill = "Condition")+
  theme_minimal()+
  scale_fill_viridis_d(alpha = 0.7)
```

```{r}
gg_frequency%>%
  filter(Type == "Low_Frequency")%>%
  ggplot(aes(x=Feature, y=Z_Score, fill = Y))+
  stat_summary(geom = "bar", fun.y = mean, position = "dodge")+
  stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge")+
  labs(title = "Low Frequency Domain Features By Condition",
       fill = "Condition")+
  theme_minimal()+
  scale_fill_viridis_d(alpha = 0.7)
```

```{r}
gg_frequency%>%
  filter(Type == "Heart_Rate")%>%
  ggplot(aes(x=Feature, y=Z_Score, fill = Y))+
  stat_summary(geom = "bar", fun.y = mean, position = "dodge")+
  stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge")+
  labs(title = "Heart Rate By Condition",
       fill = "Condition")+
  theme_minimal()+
  scale_fill_viridis_d(alpha = 0.7)
```


```{r}
gg_time%>%
ggplot(aes(x=Feature, y=Z_Score, fill = Y))+
  stat_summary(geom = "bar", fun.y = mean, position = "dodge")+
  stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge")+
  labs(title = "Time Domain Features By Condition",
       fill = "Condition")+
  theme_minimal()+
  scale_fill_viridis_d(alpha = 0.7)
```

```{r}
rhrvPlot = rhrv%>%
  MakeHRVObject()

rhrvPlot = InterpolateNIHR(rhrvPlot, freqhr = freq, method = "spline")

rhrvPlot = CreateFreqAnalysis(rhrvPlot)
      
zero_proportion = length(which(rhrvPlot$HR == 0))/length(rhrvPlot$HR)
  
      if(zero_proportion <= 0.05){
        size = 300 #width of sliding window used to calculate frequency domain features, set at 1 minute
        shift = 30 #the step size of the window in seconds
      }else{
        message("Using non-default frequency variable window")
        size = 120 #width of sliding window used to calculate frequency domain features, set at 1 minute
        shift = 1 #the step size of the window in seconds
      }
      
      rhrvPlot = CalculatePowerBand(rhrvPlot, indexFreqAnalysis = 1, size = size, shift = shift)
```


```{r}
capt = expression(Power~bands~calculated~"in"~ms^{2})

do.call(cbind, rhrvPlot$FreqAnalysis[[1]][1:7])%>%
  as_tibble()%>%
  mutate(Section = paste0("Section", rep(1:6, each = ceiling(n()/6), length.out=n())),
         Time = Time/60)%>%
  gather("Feature", "Value", 1:6)%>%
  ggplot(aes(x=Time, y=Value))+
  facet_grid(Feature~Section, scales = "free")+
  geom_line()+
  labs(x = "Time (mins)",
       y = "Value",
       title = "Time Series of Frequency Power Band\n30 Minutes Leading Up To Eating Episode",
       caption = capt)+
  theme_minimal()+
  scale_x_continuous(breaks = seq(0, 30, by = 1))
```

